POST http://localhost:8082/cart/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyYXZpQGdtYWlsLmNvbSIsImlhdCI6MTc4OTAzNDUwMywiZXhwIjoxNzg5MDM2MzAzfQ.--1H4dDzKjxokuTXIw5w4zgGfY1OYJ5Y154L13qpXbo
Content-Type: application/json

{
  "cartItemRequestDTOS": [
    {
      "productId": 2,
      "quantity": 7
    },
    {
      "productId": 1,
      "quantity": 5
    }
  ]
}
